### ISSUE TITLE
Intro to CSS Lab

### ISSUE THREAD

**Issue by FeniusFarsaid** [learn-co-curriculum/css-essentials-introduction-to-css-lab#2]
The Intro to CSS Lab contains a small error similar to the error in the HTML album cover lab. The style.css file contains the line "color: red}" with an unopened bracket. "learn" will pass all correctly performed tasks above that line. The only task after that line (change font-style to italic) will fail until the original code is corrected but "learn" will locate the error in the font-style line.

**Comment by maxwellbenton** [comment]
Hi @FeniusFarsaid,

Thank you for opening this issue. Your feedback has identified a problem with this lab's tests that was allowing invalid CSS to pass. We've updated this lab by adding an additional CSS validation test, as it was previously only checking to see if specific content was present in `style.css`. 

Please note with this update - although Learn has registered your completion of this lab, your solution is not valid CSS. Take a look at this lesson's [provided solution](https://github.com/learn-co-curriculum/css-essentials-introduction-to-css-lab/blob/solution/style.css) and [compare to your solution](https://github.com/FeniusFarsaid/css-essentials-introduction-to-css-lab-online-web-prework/blob/master/style.css) to see.

We apologize for any inconvenience this may have caused, but thank you for bringing this issue to light and helping to ensure future students do not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
